### ISSUE TITLE
Fan Speed

### ISSUE THREAD

**Issue by Raphael713** [jane-t/rpi-fanshim#1]
Hello Jane,
Rapa from forum Pimoroni here...

Is it possible to include a setting for the fan speed in this plugin?

Reason: My pi is mounted vertically (screwed on the back of the TV) and the fan really doesn´t like to reach full speed when it´s vertical, it makes a loud noise =(

**Comment by jane-t** [comment]
Unfortunately there are no examples of controlling the speed on the FanShim the example code just does an on or off option, which is what my plug in does.

Have you come across any examples of code controlling the Fan Shim Speed?

**Comment by Raphael713** [comment]
I didn´t found the code, however seens like @grayerbeard has a working code.

ref: https://github.com/pimoroni/fanshim-python/issues/22 
https://www.smalle.uk/r-pi-4-blog

**Comment by jane-t** [comment]
He has not published the code yet as he is still testing according to his blog.

Once his code is out I will try and take a look,  but I am not very experienced with Python,  so it may be too difficult for me to work out how it works,  as it probably won't be a simple "drop in"

**Comment by Raphael713** [comment]
I understand, I´m still learning the basic, so I can´t help either =(

**Comment by grayerbeard** [comment]
Sorry folks now 70 year old brain is struggling a bit to get back into the code after being away from home for a few weeks.  I had started tidying up a bit and had forgotten where I had got to.   Doing Python with a brain with bad short term memory is "interesting", 
If you look at the site you will see a snap shot of it working.  If you want to use my method you only really need the basics of the algorithm for figuring out what PWM values to use which I will post an explanation about in the next few days.
There is only a narrow range of frequencies etc that are reliable otherwise the FanShim does not rotate.   However using PWM is worthwhile as using PWM means it runs much quieter for all but extreme loads which I have only managed to trigger by running load test software.

**Comment by grayerbeard** [comment]
Code is now posted and downloadable onat address posted above. (R Pi Blog)

**Comment by jane-t** [comment]
Thanks I will try and review the code when I can,   I suspect the problem will be not all of the extensive includes you have used will be available on libreelec.

**Comment by grayerbeard** [comment]
> Thanks I will try and review the code when I can, I suspect the problem will be not all of the extensive includes you have used will be available on libreelec.
I did a little research and it does seem messing with anything in Python is difficult in Livbreelec. See https://forums.pimoroni.com/t/using-fanshim-software-on-kodi-libreelec/11790/5  
Please see simplified and more proven at https://github.com/grayerbeard/R_Pi_4_Fanshim_PWM.  
The advantage of my code compared to the pimorini is that its all in the install directory for you to mess with to see where the problem is and extract the bit you need.

**Comment by polojoe** [comment]
This script implements 3 speed levels for an argon40 case, could this also be implemented for fanshim?
https://download.argon40.com/argonone-setup-libreelec.sh

**Comment by jane-t** [comment]
I am not sure and I can't easily test Sorry
